id: P001803
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W18139
  title: རྒྱུད་གསང་སྙིང་གི་འགྲེལ་པ་རིག་འཛིན་དགྱེས་པའི་ཞལ་ལུང
  author: ''
  volumes:
    de6362a7cd2944c1a0648b968a93154e:
      image_group_id: I1KG1619
      title: ''
      volume_number: 1
      total_pages: 114
      base_file: v001.txt
